### ISSUE TITLE
Setting to disable the zooming

### ISSUE THREAD

**Issue by paulvt** [chrisbevan/skin.pellucid#1]
I would like to request a setting that I also requested for Maximinimalism, namely to disable the zooming effect.  It gradually heats my CPU up to 80° at which temprature the varying fan frequency starts to get to me. :)

**Comment by chrisbevan** [comment]
Ouch.. Yep. I can do that.
Out of interest, what's your setup?

**Comment by paulvt** [comment]
Not that low-powered either: an Intel NUC with an Intel i3-3217U CPU.

**Comment by chrisbevan** [comment]
Option added in latest GIT

**Comment by paulvt** [comment]
Cheers! That is definitely keeping the fan down when playing music (especially with this heat wave going ;)).
However, except for the artist slideshow when playing music, the rest of the interface still has zooming stuff here and there (main menu..)

**Comment by chrisbevan** [comment]
Yeah - the setting only affects the looped fade / zoom effect used on the background imagery at the moment.

I'd be keen to keep the other zooms if I can.. Do they still cause overheating?

**Comment by paulvt** [comment]
Well, sometimes I put some music on via the webinterface/remote app, so then the interface lingers in the main menu.  Then, yes, it seems to be as heavy as the zooming in music fullscreen (which is artist slideshow, I presume).   Enabling "start music visualisation immediately" helps though, so no lingering in the interface at least.
