### ISSUE TITLE
Stream not played in background when navigating menus

### ISSUE THREAD

**Issue by fipm** [chrisbevan/skin.pellucid#10]
I am not sure if it is intended behaviour or not, but I noticed that unlike with maximinimalism - which I love dearly! - when navigating the menus with a stream playing, the stream does not replace the background.

**Comment by chrisbevan** [comment]
Hi fipm,

It is intended behaviour i'm afraid. Allowing fullscreen video behind the menus just doesn't suit the design I was going for!

**Comment by chrisbevan** [comment]
BTW: I'll be returning to Maximinimalism shortly, preparing version 2.0 for a Krypton release.

**Comment by fipm** [comment]
Great news! Can't wait for it!

**Comment by chrisbevan** [comment]
Fixed in Pellucid Krypton branch
