### ISSUE TITLE
Add easy way to start party mode

### ISSUE THREAD

**Issue by paulvt** [chrisbevan/skin.pellucid#12]
Currently, there is no easy way to start playing party mode using the default party mode playlist.
The only was is to go to Music, then Playlists, then select the "Party mode playlist" , open the context menu and select "Play in party mode". 

I actually use this very often if I don't want to bother with selecting an album and currently just use Chorus2 or an app on my phone to start it.  Most skins seems to support it though (which is by no means the reason that you should add it as well ;)).

**Comment by chrisbevan** [comment]
Agreed. I'll find a good place to put it.
