### ISSUE TITLE
Kodi 16.1 on Rpi2: Generating background for Music section takes long time

### ISSUE THREAD

**Issue by cczarski** [chrisbevan/skin.pellucid#14]
Hi Chris,

tried the Pellucid skin today - really nice and, for me, the first serious alternative to Maximinimalism. However, on a Raspberry Pi 2 (with Kodi 16.1 (osmc)), the background rendering for the music section takes about 2 or 3 seconds - during that time kodi is stalled. The music library contains about 250 albums with a "folder.jpg" file.
An option to turn that dynamic background off ( or a more generic "low cpu" option ) would be great ...

Best regards

Carsten

**Comment by chrisbevan** [comment]
Hi Carsten, thanks for getting in touch!

Development for the Jarvis version of Pellucid has ended in favour of Kodi 17 (Krypton). I'm not sure of OSMC's development cycle, but if you can upgrade then that should solve this particular issue.

N.B: Pellucid is now on the official Kodi repo for Krypton.

**Comment by cczarski** [comment]
Hi Chris,

thanks for the quick response - so I'll have a look at the Krypton version again. 

Best regards from cold Munich

Carsten

**Comment by chrisbevan** [comment]
Welcome! 

Happy New Year from a not-much-warmer Bristol!
