### ISSUE TITLE
Add/improve music videos support

### ISSUE THREAD

**Issue by paulvt** [chrisbevan/skin.pellucid#17]
As a wishlist feature, music video support could be added and improved.  I manually added the library item to the Music section menu, but it doesn't work very well. The first page is a list and is fine: Genres, Directors, Albums, etc.  But if I then go to Albums I get portrait-sized tiles grid without text (the lists of albums) and if I enter those I get some portrait-sized tiles with the track name, but without the track number and such and the tiles don't carry the (in most cases landscape) thumbnails so it's a bit hard to navigate.

It kind of reminds me of the previous state of the photo library actually, so maybe it is as easy as to define which kind of view is used?

**Comment by paulvt** [comment]
As a side question, if I manually edit the menus by adding some addons and you add items to the skin, do I get to see your additions or do I need to reset and readd them, i.e. is the menu editing an overlay of the default or a editted copy?

**Comment by chrisbevan** [comment]
Thanks Paul, i'll look into it.

Unfortunately you'll need to reset the menus to default to pull though any changes I make. Sorry for the inconvenience. I'll probably add in music videos as a default item, so may be worth waiting a little for that work to be completed.

**Comment by paulvt** [comment]
Cheers! It works nicely yeah.

**Comment by chrisbevan** [comment]
Cool - cheers!
