### ISSUE TITLE
stretched tv channel logos

### ISSUE THREAD

**Issue by andreineculau** [chrisbevan/skin.pellucid#2]
Took pellucid for a spin yesterday and noticed that the tv channel logos are stretched, whereas maximinimalism shows them as cropped. The latter looks better imho

**Comment by chrisbevan** [comment]
Yeah. I think the reason I cropped them last time was due to some less than perfect channel logos. 

Chances are that any new version of Maximinimalism will be based upon Pellucid (they share much of the same underlying structure), so that aspect ratio will be carried through.
