### ISSUE TITLE
custom background images are stretched

### ISSUE THREAD

**Issue by eleith** [chrisbevan/skin.pellucid#20]
not sure if this is an issue or working as expected, but when i set my custom background folder to my photos folder, the images are stretched to fit the screen.

is it expected that i do the resizing? or should the skin be cropping/resizing for me?

**Comment by chrisbevan** [comment]
Hi eleith,

The aspect ratio for the background images loader is currently set to "stretch", based on a lazy assumption that the images will always be 16x9. I'll change this up in the next update to something more sensible.

I'll reply again when the changes are pushed to Github.

**Comment by eleith** [comment]
glad to hear it!

pellucid is my favorite kodi theme. perfect balance of functionality with minimalism. great job.

**Comment by chrisbevan** [comment]
No worries. An update has just been pushed to Github. Unfortunately none of the options for aspect ratio are perfect, but at least now your images will maintain their own ratio.
