### ISSUE TITLE
Pellucid skin chrashes after stop playing music

### ISSUE THREAD

**Issue by TheNoTwist** [chrisbevan/skin.pellucid#22]
The skin is crashing when the music is stopped which is currently playing.
It can be reproduced if you do the following steps:
- start playing music
- go the home screen
- go to fullscreen where you can see the current track and the pictures of the band
- open the menu on the right
- stop the music

The music will be stopped. The skin tries change back to the home screen. 
After the steps above, the do not respond anymore.

If you start playing music and toggle to fullscreen without going to the home screen, the skin won't crash.

**Comment by chrisbevan** [comment]
Thanks. I have literally just pushed a fix for this. Are you testing against the very latest GIT code?

**Comment by TheNoTwist** [comment]
Thank's for the quick response. I have installed the skin out auf the Kodi-Repository. I assume that is not the newest version. 

I will try latest GIT code.

**Comment by TheNoTwist** [comment]
It works :-)
