### ISSUE TITLE
Music playlist view doesn't work correct

### ISSUE THREAD

**Issue by TheNoTwist** [chrisbevan/skin.pellucid#26]
Hi,

may be there is something wrong in the music playlist view. I have created some music playlists and when I want to view the content of the play list it looks like this:

![grafik](https://cloud.githubusercontent.com/assets/26326120/26755066/3a2ddc5e-4886-11e7-8278-918863a86e20.png)

The Title of tracks are not completely visible. For each track I should see an individual name.
In addition something overlayes the playlist on the right side.

Is this a bug or am I doing something wrong?

Regards
Matthias

**Comment by chrisbevan** [comment]
Fixed in 1.2.4
