### ISSUE TITLE
Missing space in add-on information dialog

### ISSUE THREAD

**Issue by solbero** [chrisbevan/skin.pellucid#27]
The add-on author field in the add-on information dialog is missing a space between "By" and "$AUTHOR". The relevant lines are https://github.com/chrisbevan/skin.pellucid/blob/master/1080i/DialogAddonInfo.xml#L121-L128

![screenshot000](https://user-images.githubusercontent.com/7732292/27805690-7d84595c-6036-11e7-9488-6196ba4f734e.png)

**Comment by chrisbevan** [comment]
Thanks - will get that fixed up
