### ISSUE TITLE
Home screen items will only auto hide on exit to homescreen 

### ISSUE THREAD

**Issue by solbero** [chrisbevan/skin.pellucid#35]
I do very much like the new auto-hide feature added to the homescreen in 1.3.1. However, I have noticed that the menu items on the homescreen only will auto-hide on the first exit to the homescreen.

If the menu items are hidden after 20 seconds and I press a button to bring them into view, then they won’t auto-hide again. To make them auto-hide, I have to enter any menu, and then exit to the homescreen again.

My guess is that the alarm in [Line 7](https://github.com/chrisbevan/skin.pellucid/blob/89477a30dd4bd0aabbdcc49dee4e2355d64e56e5/1080i/Home.xml#L7) in [home.xml](https://github.com/chrisbevan/skin.pellucid/blob/89477a30dd4bd0aabbdcc49dee4e2355d64e56e5/1080i/Home.xml) is not reset on key presses after the menu items are hidden, but only on exits to the homescreen.

Is this anything you could prioritise to fix in the current Krypton build?

**Comment by chrisbevan** [comment]
Hi Solbero,

I'll look into it, but in the meantime you can minimise the menu at anytime using the down arrow button (near the power / settings).
