### ISSUE TITLE
High CPU load in Homescreen with equaliser.gif

### ISSUE THREAD

**Issue by kaputt3** [chrisbevan/skin.pellucid#36]
Similar to RSS feeds in the last few versions of Kodi, the CPU load goes up when there is free CPU time just so that rendering is improved to perfection. This is a problem on my ARM device. It can be changed by replacing your equaliser logo with some static image. Not as good looking, but far better than a board that goes to 85 degrees instead of being almost idle.

Loving the skin btw. Great job.

**Comment by chrisbevan** [comment]
Thanks for reporting kaputt3. I must have missed that one. Amazing how much damage a tiny gif can do!

Will get that fixed up for you asap.

**Comment by chrisbevan** [comment]
Quick question: Are you using an RPi or some other flavour of ARM based device?

**Comment by kaputt3** [comment]
Odroid C2, I think Raspberry may be more efficient but its been a while that I have used them.

**Comment by paulvt** [comment]
Also the "current playtlist" uses the equaliser (and it is the view Kodi switches to when starting to play an album, even using the web interface/remote app). The rest seems to be a play icon now, which indeed helps a lot, wow.
