### ISSUE TITLE
Main Menu from add-ons like Netflix/Amazon Videos is stuck on screen

### ISSUE THREAD

**Issue by ahpatel** [chrisbevan/skin.pellucid#47]
Running into a bug on v18 where the menu from Netflix/Amazon type plugins is overlaid on top of the show selection screen.  (screenshots from Netflix provided for clarity).  

Once I click into something from the menu on the main level (i.e., New Releases), the shows pop up and can be selected (notice the selection is highlighting the "Great News" show in screenshot 2), but the main Netflix menu stays visible on top.

https://imgur.com/wGyXipO
https://imgur.com/fx76lBE

**Comment by loggio** [comment]
You can reproduce this if you open up your tv shows local  library, select a show, go into season view, then into episode view.
 Then press backspace until you're back in the main menu...

Then launch an addon like YouTube or netflix and the views are overlapped. The only way to fix this is to reload the skin.

It's almost like a caching issue, or that kodi is rendering the view before the addon can tell kodi what the content type is... 

I've tried fixing this changing the different variables in the includes.xml
But couldn't figure out what was causing this.

This only happens when transitioning from a local library list to an addons list.

**Comment by loggio** [comment]
Interesting as I couldn't reproduce this on android... But my linux/raspberry pi setups do it without fail every time.

I'll try windows and report back.

**Comment by ahpatel** [comment]
I can confirm these steps reproduce the issue on a Windows 10 system.

**Comment by ahpatel** [comment]
@loggio - I also found that the overlay which gets stuck is from the first video addon you open on a Kodi 'first load'.  I used Netflix in the first post, but here's a flow that may help narrow down the area of code...

1. Restart Kodi or reload the skin to start fresh.
2. Open ESPN3 (or Amazon or some other Video addon) and click into the menu one level deep. (should work as expected without the overlay issue)
3. Exit out and go into your local library.  Click into a show.
4. Exit out and open up Netflix.  Notice that the ESPN3 menu is still the one that's overlaid on top of Netflix.

**Comment by loggio** [comment]
Ok...I think i've found the fix. 

It's realy quite simple, you just have to tell kodi to reset the path history when exiting MyVideoNav windows using a kodi built in function.

Add this line to MyVideoNav.xml direclty under the <onload> commands at the top.
    <onunload>Container.Update(path,replace)</onunload>

@ahpatel l, if you get a chance can you please test this fix on your end and report back. I gave it a quick test on my linux machine and it worked fine. Don't have the time to test any further today though.

**Comment by ahpatel** [comment]
@loggio confirmed working on Windows 10.  Thanks for the effort.

**Comment by loggio** [comment]
Great, thanks.

**Comment by ahpatel** [comment]
@loggio the fix has a small side effect... 
So, if I'm in TV Shows -> Series -> Episode and watch an episode to completion, it used to take me back to the Episode screen after the episode ended.  Now it does this...
https://imgur.com/6EPmXe3
That is, it exits out onto a blank screen with the video section menu (slideout menu from the left side) focused.  Hitting back or exit takes me back to the home screen.  Removing the container.update code resolves it.

Have you encountered the same thing?

**Comment by loggio** [comment]
Ah ok ... Didn't think of that..
remove that line of code... It won't work.

try this instead...
    < onload condition="String.Contains(container.folderpath,plugin://)" >Container.SetViewMode(54)< /onload >

Mind you this is a hacky solution.... The real issue i'm guessing is with View type visibility conditions... But there are quite a lot of expressions being used in Pellucid to determin the visibility of certain view types and it's a bit of a nightmare trying to locate what's causing this.

I'll have to leave this one with @chrisbevan to fix...

**Comment by ahpatel** [comment]
That works.  Thanks again.
