### ISSUE TITLE
Filename casing

### ISSUE THREAD

**Issue by paulvt** [chrisbevan/skin.pellucid#5]
I run Pellucid from the Git repository, which works great. However, two files are cased differently than how they are used/named in the skin (according to Kodi logs) so I added symlinks to make it work:

```
./1080i/DialogOK.xml -> DialogOk.xml
./extras/playlists/collage_randomMovies.xsp -> collage_RandomMovies.xsp
```

Feel free to ignore this, but I'd wanted to report it anyway. (I think I also have the DialogOk link for Maximinalism already ;))

**Comment by chrisbevan** [comment]
Thanks for spotting - i'll get this fixed up ASAP.
