### ISSUE TITLE
Posters for TV shows blown up and blurry

### ISSUE THREAD

**Issue by robmcc1983** [chrisbevan/skin.pellucid#50]
Hi mate,
This is not necessarily a issue but it does let down the rest of this skin in my opinion.
This only effect TV shows.
When I select a TV show it has a poster on the left hand side for that TV show, the only problem is that it's zoomed in and makes the scraped posters look jaggered on the edges and blurred to look at.
Would it not be possible to have them appear like say the music albums do with a poster in the center of the left hand side.
Thanks
Rob

**Comment by robmcc1983** [comment]
Here is a example you can't really see the jaggered edges and blur on the photo I have taken but you can see that it is zoomed in quite some.

![img_20190214_160309](https://user-images.githubusercontent.com/19917296/52799604-151ae580-3072-11e9-9cde-9dd8045cd3fd.jpg)

**Comment by robmcc1983** [comment]
Could we not have TV shows something like this.

Thanks

![img_20190214_160518](https://user-images.githubusercontent.com/19917296/52799762-662ad980-3072-11e9-90a3-9b0695eb5abb.jpg)

**Comment by chrisbevan** [comment]
Thanks for reporting, but I'm not likely to make those changes i'm afraid. I would suggest looking at your content scrapers and seeing if you can increase the quality of the images it downloads.

**Comment by robmcc1983** [comment]
Brill thanks for that.
Do you know how I increase the quality of images in the default scrapers Kodi uses.
Thanks

**Comment by chrisbevan** [comment]
Sorry bud, i'm just a skinner :-)
I would suggest looking at the Artwork Beef addon and reading up on the support for that.
