### ISSUE TITLE
Menu auto hide is causing add-ons to unfocus from listitem (fix included)

### ISSUE THREAD

**Issue by dumbie** [chrisbevan/skin.pellucid#53]
When I open an add-on the home menu auto hide function is causing listitems to get unfocused because the AlarmClock timer does not stop when an add-on is opened, this is especially annoying when you are not using a mouse because moving up and down on a remote does not reactivate or focus back on the listitems.

It would be great if you can add a setting to the skin to disable the auto hide function completely or if you can add the following fix to the skin so the timer gets cancelled when you open an add-on or other window:

Change the following in "Home.xml" to workaround the issue:
`<onload>AlarmClock(hidemenu,setfocus(9999),00:20,true)</onload>
**<onunload>CancelAlarm(hidemenu,true)</onunload>**`

Just wanted to let you know this small issue and how to fix it :)

Thanks for the great skin and greets,
Dumbie

**Comment by chrisbevan** [comment]
Thanks Dumbie, i'll include that fix in the next update.

Cheers!
