### ISSUE TITLE
Art in wall view not showing up

### ISSUE THREAD

**Issue by 22350** [chrisbevan/skin.pellucid#55]
Addon is set to  "wall view" art showing up with black boxes. When i roll on top of the selection, the art pops up in the background.

 only one addon has this issue. others works fine.

kodi 18.5 on linux

**Comment by 22350** [comment]
![IMG_3112](https://user-images.githubusercontent.com/2864726/69750079-bc986e80-1100-11ea-8b36-d55011f46e80.jpg)

seems the skin is seeing the art, but not placing it in the squares

**Comment by chrisbevan** [comment]
Hi,

Sorry - this is not a skin related issue and I do not support addons. Please contact the creator of the Addon.

**Comment by 22350** [comment]
thats strange, given this is the only skin that seems to have this issue.  there seems to be a couple of other user on your kodi page, who have had the same issue. skin sees the art (posts it in the background) but it doesnt show up in the wall,

obviously i can just use a different skin, but yours is really nice,

regardless, great work on the skin,
