### ISSUE TITLE
Rating support

### ISSUE THREAD

**Issue by ask6155** [chrisbevan/skin.pellucid#56]
Hello.
I like using the pellucid skin on my TV but I would like to have a rating on the shows and movies I have.
on the information page there could be a rating next to the description stating PG-13 or R or whatever.
Is it possible to add this?

Thanks in advance

**Comment by joaomariord** [comment]
I am also interested in this, and I'm offering myself to do this.
Only need guidelines from the professionals.

**Comment by chrisbevan** [comment]
Hi,

Sure: here's the list of labels available: https://kodi.wiki/view/InfoLabels#ListItem

I won't add this to the official release as the MPAA ratings are very US centric.

However, to add the rating label, the code is: $INFO[ListItem.Mpaa]. The file you want is 1080i/DialogVideoinfo.xml. Potential places to display this are contained in lines 109 - 190.

**Comment by joaomariord** [comment]
> Hi,
> 
> Sure: here's the list of labels available: https://kodi.wiki/view/InfoLabels#ListItem
> 
> I won't add this to the official release as the MPAA ratings are very US centric.
> 
> However, to add the rating label, the code is: $INFO[ListItem.Mpaa]. The file you want is 1080i/DialogVideoinfo.xml. Potential places to display this are contained in lines 109 - 190.

Do I make a pull request (despite not going to the official release) or publish a patch here?
