### ISSUE TITLE
Kodi Matrix v19 Support or Planned

### ISSUE THREAD

**Issue by konradwalsh** [chrisbevan/skin.pellucid#59]
Is there planned support for v19 Kodi?
Or does anyone know a way to make it work?

I tried amending the addons.xml to say 5.15.0 but still fails.. I am guessing its supporting plugins are failing too

**Comment by mooninite** [comment]
The master branch works with v19.

**Comment by konradwalsh** [comment]
> The master branch works with v19.

Except
It doesn't

**Comment by chrisbevan** [comment]
No need to wipe config.

Is the skin shortcuts addon installed on your system? Unfortunately, until I release the V19 version via the official repo, this dependency needs to be installed manually. 

Shouldn't be too long now until the v19 release goes live on the Kodi repo, just running some final checks.

**Comment by chrisbevan** [comment]
BTW Konrad, did we turn out to have a mutual friend in Galway?

**Comment by konradwalsh** [comment]
> BTW Konrad, did we turn out to have a mutual friend in Galway?

i cant remember how far we got with this... Do you know Eddie Foster?
