### ISSUE TITLE
Grey bars in "Video" menu

### ISSUE THREAD

**Issue by bgeVam** [chrisbevan/skin.pellucid#6]
If I click "Video" in the main menu, i get the following get the following view:
![screenshot000](https://cloud.githubusercontent.com/assets/11328579/14468755/712bafbc-00e1-11e6-8a20-a0de269f5676.png)
The "grey" bars, as you can see them on the top of the screenshot don't seem intended to me(?)
I experienced this on
Windows 10
Openelec
with KODI Jarvis 16.1 RC 2

NOTE: Maybe this is because I have absolutely nothing in my library?

I would recommend to show the same images as in the main menu here (the girl for "Video" and the LP for "Music")

**Comment by chrisbevan** [comment]
Hi bgeVam,

Those grey bars are file list items (push right to access). This is the current default for users without libraries.

I do intend to improve the handling of non-library based users for the V1 release. Good suggestion about carrying through the home screen images - i'll make a note to do that!
