### ISSUE TITLE
Photo library looks weird

### ISSUE THREAD

**Issue by paulvt** [chrisbevan/skin.pellucid#8]
For the text is behind the thumbnails of a album (folder).  The highlighted album/folder gets a white background and the label also turns white, making it unreadable.

**Comment by chrisbevan** [comment]
Thanks Paul. That section does need work. I'll get it fixed up ASAP.

**Comment by paulvt** [comment]
Also I noticed that if I dive into albums/folders, the back buttons brings me to the side menu instead of one level up? I hope that the view can support this without me needing to enable the ".." items throughout the entire interface?

**Comment by chrisbevan** [comment]
Hmm. Yes, that should have been fixed up. Are you running the latest code?





On Fri, May 27, 2016 at 12:05 PM, Paul van Tilburg <notifications@github.com

**Comment by paulvt** [comment]
Yes, I use git master (well, I pulled last Sunday).

**Comment by chrisbevan** [comment]
OK. Let me look into that. I know it works on my setup (Libreelec and OSX) 

Expected behaviour of course is for the back button to only expose the side menu when there is no parent directory (only an issue for files, genres, artists etc). Like you, I have no desire to have the '..' folder items. 

What's your setup?

**Comment by paulvt** [comment]
Kodi 16.1 on Linux; picture-wise it is several sources with nested folders containing albums in the leaves.
I tried just now on my laptop too.. there I browse: Photos > 2015 > Holidays > [Some album].
If I press Backspace, I get the sidebar, not what's in "Holidays".

**Comment by chrisbevan** [comment]
No worries. I'll work on that (pic views have gotten waylaid somewhere -
probably because I rarely use it). Can you confirm that the back button is
working as expected within the music sections (genre, artist, etc)?

**Comment by paulvt** [comment]
Yeah, Videos/Music menu is fine. That's why I noticed it when I wanted to show pictures yesterday..

**Comment by paulvt** [comment]
Ah, the same thing happens when browsing Files in the Videos menu.

**Comment by chrisbevan** [comment]
Thanks. Should be fixed now.

God, visibility logic for Kodi's node system is such a ballache!

**Comment by paulvt** [comment]
Yes, works (both browsing Pictures and and browsing the Files section in Video and Music).  Also the pictures library looks nice. :)
Thanks!

**Comment by chrisbevan** [comment]
No problem!

BTW: I'll be moving on to Krypton updates shortly. With any luck, the
changes to the skinning engine there will allow me to finally release the
skin on the official repository and get back to updating Maximinimalism.

Thanks again for your support, it's hugely appreciated.
