### ISSUE TITLE
Remove star on movie cover

### ISSUE THREAD

**Issue by FomaFomitch** [chrisbevan/skin.pellucid#83]
Hello, can't find how to delete this star (it's on every movie cover of my collection) ?
![image](https://user-images.githubusercontent.com/74829959/144916229-c227e788-d18c-480c-b5be-99f22491b614.png)

**Comment by DrGogu** [comment]
It may mean the movie is unwatched I think.

**Comment by ohhmyy** [comment]
Hi. Yes, the star marks the content that has not been watched yet. There is no option to turn it off. But you can easily do it yourself by changing the View_Movies.xml.
https://github.com/chrisbevan/skin.pellucid/blob/master/1080i/View_Movies.xml

In lines 288 and 358 you could change the visible condition to make it not visible anymore:
So change
`<visible>String.IsEmpty(ListItem.PlayCount)</visible>`
to
`<visible>false</visible>`

**Comment by FomaFomitch** [comment]
Thanks!
