### ISSUE TITLE
Youtube Adddon information not displayed

### ISSUE THREAD

**Issue by bgeVam** [chrisbevan/skin.pellucid#9]
The Youtube Addon is among the most used Addons. If someone wants to login with his/her user account, on the top right of the screen, a message gets displayed, showing the User 2 codes which need to be entered [here](youtube.com/activate) in order to get the login working.

The issue:
unfortunatley the code isn't displayed, because the "top right corner information box" offers to little space for this information. Always switching to confluence is not quite comfortable for the users. I experienced the same issue with maximinimalism.

If you need further information - just let me know!

**Comment by chrisbevan** [comment]
Thanks bgeVam,

I think this is one to be directed to the Youtube addon creator i'm afraid. It is inappropriate to use the notification / message system you describe for that purpose! I suggest they use a dialog box control or similar.

While I can change the size of the notification box, I can do nothing about the fact that it disappears after a short period of time (the timing is hard wired into Kodi).

**Comment by bgeVam** [comment]
I am really sorry for my noob-question. But if it works in Confluence, why shouldn't it work in pellucid? The developers of the youtube addon don't know which design is used by the end user, so they can't change this in my opinion.

**Comment by chrisbevan** [comment]
No such thing as a noob question in my book :-) 

A fair point. I will look into it and see if Confluence is doing something that i've missed. 
If I get chance, i'll have a chat with the Youtube addon people directly about this also.
