### ISSUE TITLE
Request:  Disable movie fanart during seeking/pause

### ISSUE THREAD

**Issue by DrGogu** [chrisbevan/skin.pellucid#95]
When seeking or pausing, fanart or movie icon is displayed in the right lower corner.  It’s quite distracting, especially during seeking.  Is there a way to disable it?  I disabled extended fanart from the Pellucid skin setting menu, but it didn’t help. 

![34F836BF-F04E-448C-BE97-01C7BBDF646B](https://user-images.githubusercontent.com/44388374/167772373-9d2151f0-0670-4b48-9cde-d526a95b8dc9.jpeg)

Thanks.

**Comment by ohhmyy** [comment]
Hi. Here is not fanart but clearart or clearlogo displayed.
In DialogSeekBar.xml just change the visible condition to hide it. Change the lines 6 and 16 to
`<visible>false</visible>`
https://github.com/chrisbevan/skin.pellucid/blob/master/1080i/DialogSeekBar.xml

**Comment by DrGogu** [comment]
Thank you.  That fixed it.
Would appreciate if developer adds a setting in skin settings for this.
