### ISSUE TITLE
Is this skin maintained?

### ISSUE THREAD

**Issue by Zecho1** [chrisbevan/skin.pellucid#98]
Just checking. There are several issues that don't seem to have been addressed in a year.

**Comment by chrisbevan** [comment]
Hi Zecho1,

The skin isn't dead, but I don't have the time to maintain it as much as I used to!

**Comment by Zecho1** [comment]
I'm looking into it but I don't know a lot about the Kodi backend or XML. What I'm doing seems to be working though.
